<?php

namespace Anytv\DashboardBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * AdvertiserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AdvertiserRepository extends EntityRepository
{
    public function findAllAdvertisers()
    {     
        $query = $this->getEntityManager()->createQueryBuilder()
          ->select(array('a', 'c'))
          ->from('Anytv\DashboardBundle\Entity\Advertiser', 'a')
          ->leftJoin('a.country', 'c')
          ->getQuery();
        
        return $query->getResult();
    }
}
