<?php

namespace Anytv\DashboardBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * AffiliateUserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AffiliateUserRepository extends EntityRepository
{
    public function findAllAffiliateUsers($page, $items_per_page, $order_by, $order, $keyword)
    {
        $first_result = ($items_per_page * ($page-1));
        
        $query = $this->createQueryBuilder('au')
          ->where("au.title LIKE :keyword OR au.first_name LIKE :keyword OR au.last_name LIKE :keyword OR au.email LIKE :keyword")
          ->setParameter('keyword', "%$keyword%")
          ->setFirstResult($first_result)
          ->setMaxResults($items_per_page)
          ->orderBy('au.'.$order_by, $order)
          ->getQuery();
        
        return $query->getResult();
    }
    
    public function countAllAffiliates($keyword)
    {    
        $query = $this->createQueryBuilder('au')
          ->select('count(au.id)')
          ->where("au.title LIKE :keyword OR au.first_name LIKE :keyword OR au.last_name LIKE :keyword OR au.email LIKE :keyword")
          ->setParameter('keyword', "%$keyword%")
          ->getQuery();
        
        return $query->getSingleScalarResult();
    }
}
