<?php

namespace Anytv\DashboardBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * AffiliateRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AffiliateRepository extends EntityRepository
{
    public function findAllAffiliates($page, $items_per_page, $order_by, $order, $keyword)
    {
        $first_result = ($items_per_page * ($page-1));
        
        $query = $this->getEntityManager()->createQueryBuilder()
          ->select(array('a', 'c'))
          ->from('Anytv\DashboardBundle\Entity\Affiliate', 'a')
          ->leftJoin('a.country', 'c')
          ->where("a.company LIKE :keyword")
          ->setParameter('keyword', "%$keyword%")
          ->setFirstResult($first_result)
          ->setMaxResults($items_per_page)
          ->orderBy('a.'.$order_by, $order)
          ->getQuery();
        
        return $query->getResult();
    }
    
    public function countAllAffiliates($keyword)
    {    
        $query = $this->createQueryBuilder('a')
          ->select('count(a.id)')
          ->where("a.company LIKE :keyword")
          ->setParameter('keyword', "%$keyword%")
          ->getQuery();
        
        return $query->getSingleScalarResult();
    }
}
