<?php

namespace Anytv\DashboardBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * AffiliateRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AffiliateRepository extends EntityRepository
{
    public function findAllAffiliates($page, $items_per_page, $order_by, $order, $keyword, $country_id, $status)
    {
        $first_result = ($items_per_page * ($page-1));
        
        if($keyword && $country_id)
        {
          $query = $this->getEntityManager()->createQueryBuilder()
          ->select(array('a', 'c'))
          ->from('Anytv\DashboardBundle\Entity\Affiliate', 'a')
          ->leftJoin('a.country', 'c')
          ->where("a.company LIKE :keyword AND a.status = :status AND c.id = :country_id")
          ->setParameters(array('keyword' => "%$keyword%", 'country_id' => $country_id, 'status' => $status))
          ->setFirstResult($first_result)
          ->setMaxResults($items_per_page)
          ->orderBy('a.'.$order_by, $order)
          ->getQuery();     
        }
        elseif($keyword)
        {
          $query = $this->getEntityManager()->createQueryBuilder()
          ->select(array('a', 'c'))
          ->from('Anytv\DashboardBundle\Entity\Affiliate', 'a')
          ->leftJoin('a.country', 'c')
          ->where("a.company LIKE :keyword AND a.status = :status")
          ->setParameters(array('keyword' => "%$keyword%", 'status' => $status))
          ->setFirstResult($first_result)
          ->setMaxResults($items_per_page)
          ->orderBy('a.'.$order_by, $order)
          ->getQuery();      
        }
        elseif($country_id)
        {
          $query = $this->getEntityManager()->createQueryBuilder()
          ->select(array('a', 'c'))
          ->from('Anytv\DashboardBundle\Entity\Affiliate', 'a')
          ->leftJoin('a.country', 'c')
          ->where("a.status = :status AND c.id = :country_id")
          ->setParameters(array('country_id' => $country_id, 'status' => $status))
          ->setFirstResult($first_result)
          ->setMaxResults($items_per_page)
          ->orderBy('a.'.$order_by, $order)
          ->getQuery();    
        }
        else
        {
          $query = $this->getEntityManager()->createQueryBuilder()
          ->select(array('a', 'c'))
          ->from('Anytv\DashboardBundle\Entity\Affiliate', 'a')
          ->leftJoin('a.country', 'c')
          ->where("a.status = :status")
          ->setParameters(array('status' => $status))
          ->setFirstResult($first_result)
          ->setMaxResults($items_per_page)
          ->orderBy('a.'.$order_by, $order)
          ->getQuery();
        }
          
        return $query->getResult();
    }
    
    public function countAllAffiliates($keyword, $country_id, $status)
    {    
        if($keyword && $country_id)
        {
          $query = $this->getEntityManager()->createQueryBuilder()
          ->select('count(a.id)')
          ->from('Anytv\DashboardBundle\Entity\Affiliate', 'a')
          ->leftJoin('a.country', 'c')
          ->where("a.company LIKE :keyword AND a.status = :status AND c.id = :country_id")
          ->setParameters(array('keyword' => "%$keyword%", 'country_id' => $country_id, 'status' => $status))
          ->getQuery();   
        }
        elseif($keyword)
        {
          $query = $this->getEntityManager()->createQueryBuilder()
          ->select('count(a.id)')
          ->from('Anytv\DashboardBundle\Entity\Affiliate', 'a')
          ->leftJoin('a.country', 'c')
          ->where("a.company LIKE :keyword AND a.status = :status")
          ->setParameters(array('keyword' => "%$keyword%", 'status' => $status))
          ->getQuery();
        }
        elseif($country_id)
        {
          $query = $this->getEntityManager()->createQueryBuilder()
          ->select('count(a.id)')
          ->from('Anytv\DashboardBundle\Entity\Affiliate', 'a')
          ->leftJoin('a.country', 'c')
          ->where("a.status = :status AND c.id = :country_id")
          ->setParameters(array('country_id' => $country_id, 'status' => $status))
          ->getQuery();     
        }
        else
        {
          $query = $this->getEntityManager()->createQueryBuilder()
          ->select('count(a.id)')
          ->from('Anytv\DashboardBundle\Entity\Affiliate', 'a')
          ->leftJoin('a.country', 'c')
          ->where("a.status = :status")
          ->setParameters(array('status' => $status))
          ->getQuery();  
        }
        
        return $query->getSingleScalarResult();
    }
    
    public function findAllAffiliatesByCountry($country_id, $status)
    {
      $query = $this->getEntityManager()->createQueryBuilder()
          ->select(array('a', 'c'))
          ->from('Anytv\DashboardBundle\Entity\Affiliate', 'a')
          ->leftJoin('a.country', 'c')
          ->where("a.status = :status AND c.id = :country_id")
          ->setParameters(array('country_id' => $country_id, 'status' => $status))
          ->orderBy('a.company', 'ASC')
          ->getQuery();   
      
      return $query->getResult();
    }
    
    public function getMaxAffiliateId()
    {    
        $query = $this->createQueryBuilder('a')
                      ->select('max(a.affiliateId)')
                      ->getQuery();
        
        return $query->getSingleScalarResult();
    }
}
