<?php

namespace Anytv\DashboardBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ConversionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ConversionRepository extends EntityRepository
{
    public function findAllConversions($page, $items_per_page, $order_by, $order, $affiliate = null)
    {
        $first_result = ($items_per_page * ($page-1));
        
        $query = $this->createQueryBuilder('c');
        
        if($affiliate)
        {
          $query = $query->where("c.affiliate = :affiliate AND c.status = :status")
                         ->setParameters(array('affiliate'=>$affiliate, 'status'=>'approved'))
                         ->setFirstResult($first_result)
                         ->setMaxResults($items_per_page)
                         ->orderBy('c.'.$order_by, $order)
                         ->getQuery();  
        }
        else
        {
          $query = $query->setFirstResult($first_result)
                         ->setMaxResults($items_per_page)
                         ->orderBy('c.'.$order_by, $order)
                         ->getQuery();  
        }
          
        return $query->getResult();
    }
    
    public function countAllConversions($affiliate = null)
    {    
        $query = $this->createQueryBuilder('c')
                      ->select('count(c.id)');
        
        if($affiliate)
        {
          $query = $query->where("c.affiliate = :affiliate AND c.status = :status")
                         ->setParameters(array('affiliate'=>$affiliate, 'status'=>'approved'))
                         ->getQuery();
        }
        else
        {
          $query = $query->getQuery(); 
        } 
          
        return $query->getSingleScalarResult();
    }
    
    public function getMaxConversionId()
    {    
        $query = $this->createQueryBuilder('c')
                      ->select('max(c.conversionId)')
                      ->getQuery();
        
        return $query->getSingleScalarResult();
    }
}
