<?php

namespace Anytv\DashboardBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ReferralRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ReferralRepository extends EntityRepository
{
    public function findAllReferrals($page, $items_per_page, $order_by, $order, $referrer = null)
    {
        $first_result = ($items_per_page * ($page-1));
        
        $query = $this->createQueryBuilder('r');
        
        if($referrer)
        {
          $query = $query->where("r.referrer = :referrer")
                         ->setParameters(array('referrer'=>$referrer))
                         ->setFirstResult($first_result)
                         ->setMaxResults($items_per_page)
                         ->orderBy('r.'.$order_by, $order)
                         ->getQuery();  
        }
        else
        {
          $query = $query->setFirstResult($first_result)
                         ->setMaxResults($items_per_page)
                         ->orderBy('r.'.$order_by, $order)
                         ->getQuery();  
        }
          
        return $query->getResult();
    }
    
    public function countAllReferrals($referrer = null)
    {    
        $query = $this->createQueryBuilder('r')
                      ->select('count(r.id)');
        
        if($referrer)
        {
          $query = $query->where("r.referrer = :referrer")
                         ->setParameters(array('referrer'=>$referrer))
                         ->getQuery();
        }
        else
        {
          $query = $query->getQuery(); 
        } 
          
        return $query->getSingleScalarResult();
    }
    
    public function getMaxReferralDate()
    {    
        $query = $this->createQueryBuilder('r')
                      ->select('max(r.date)')
                      ->getQuery();
        
        return $query->getSingleScalarResult();
    }
}
