<?php

namespace Anytv\DashboardBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * SignupAnswerRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SignupAnswerRepository extends EntityRepository
{
    public function findAllSignupAnswers($page, $items_per_page, $order_by, $order)
    {
        $first_result = ($items_per_page * ($page-1));
        
        $query = $this->createQueryBuilder('sa')
                      ->leftJoin('sa.affiliate', 'a')
                      ->leftJoin('sa.question', 'q')
                      ->setFirstResult($first_result)
                      ->setMaxResults($items_per_page)
                      ->orderBy('sa.'.$order_by, $order)
                      ->getQuery();
          
        return $query->getResult();
    }
    
    public function countAllSignupAnswers()
    {    
        $query = $this->createQueryBuilder('sa')
                      ->select('count(sa.id)')
                      ->getQuery(); 
          
        return $query->getSingleScalarResult();
    }
}
