<?php

namespace Anytv\DashboardBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * TrafficReferralRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TrafficReferralRepository extends EntityRepository
{
    public function findAllTrafficReferrals($order_by, $order)
    {
        $query = $this->createQueryBuilder('tr')
          ->orderBy('tr.'.$order_by, $order)
          ->getQuery();
        
        return $query->getResult();
    }
}
