<?php

namespace Anytv\MainBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * NewsCategoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NewsCategoryRepository extends EntityRepository
{
    public function findAllNewsCategories($page, $items_per_page, $order_by, $order)
    {
        $first_result = ($items_per_page * ($page-1));
                
        $query = $this->createQueryBuilder('nc')
          //->where('nc.status = :status')
          //->setParameter('status', $status)
          ->setFirstResult($first_result)
          ->setMaxResults($items_per_page)
          ->orderBy('nc.'.$order_by, $order)
          ->getQuery();
        
        return $query->getResult();
    }
    
    public function countAllNewsCategories()
    {    
        $query = $this->createQueryBuilder('nc')
          ->select('count(nc.id)')
          ->getQuery();
        
        return $query->getSingleScalarResult();
    }
}
