<?php

namespace Anytv\MainBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * NewsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NewsRepository extends EntityRepository
{
    public function findAllNews($page, $items_per_page, $order_by, $order)
    {
        $first_result = ($items_per_page * ($page-1));
                
        $query = $this->createQueryBuilder('n')
          //->where('n.status = :status')
          //->setParameter('status', $status)
          ->setFirstResult($first_result)
          ->setMaxResults($items_per_page)
          ->orderBy('n.'.$order_by, $order)
          ->getQuery();
        
        return $query->getResult();
    }
    
    public function countAllNews()
    {    
        $query = $this->createQueryBuilder('n')
          ->select('count(n.id)')
          ->getQuery();
        
        return $query->getSingleScalarResult();
    }
}
